/**
 * Student survey system API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QuestionType } from './questionType';

export interface AnswerDto { 
    id?: number;
    value?: string;
    questionText?: string;
    questionType?: QuestionType;
    questionId?: number;
}