/**
 * Student survey system API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CourseLecturer } from './courseLecturer';
import { CourseParticipant } from './courseParticipant';
import { Semester } from './semester';

export interface Course { 
    id?: number;
    name?: string;
    semesterId?: number;
    semester?: Semester;
    courseLecturers?: Array<CourseLecturer>;
    courseParticipants?: Array<CourseParticipant>;
}