/**
 * Student survey system API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type QuestionType = 'Text' | 'SingleSelect' | 'MultipleSelect' | 'Numeric' | 'Date' | 'Boolean';

export const QuestionType = {
    Text: 'Text' as QuestionType,
    SingleSelect: 'SingleSelect' as QuestionType,
    MultipleSelect: 'MultipleSelect' as QuestionType,
    Numeric: 'Numeric' as QuestionType,
    Date: 'Date' as QuestionType,
    Boolean: 'Boolean' as QuestionType
};