/**
 * Student survey system API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QuestionType } from './questionType';
import { ValidationConfig } from './validationConfig';

export interface QuestionDto { 
    id?: number;
    index: number;
    questionText: string;
    questionType: QuestionType;
    validationConfig?: ValidationConfig;
    values?: Array<string>;
}