/**
 * Student survey system API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SurveyListItemDto { 
    id?: number;
    name?: string;
    active?: boolean;
    isTemplate?: boolean;
    anonymous?: boolean;
    courseName?: string;
    creatorName?: string;
    endDate?: Date;
}