/**
 * Student survey system API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SurveyStatus = 'Draft' | 'Active' | 'Ended';

export const SurveyStatus = {
    Draft: 'Draft' as SurveyStatus,
    Active: 'Active' as SurveyStatus,
    Ended: 'Ended' as SurveyStatus
};